# =========================
# Build stage
# =========================
FROM maven:3.8.4-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# =========================
# Runtime stage
# =========================
FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/Hotel-Backend-Project-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 9192

ENTRYPOINT ["java", "-jar", "app.jar"]
